config/routes.rb
Rails.application.routes.draw do
  root 'firstpage#index'
  get 'firstpage/index'

  resources :trips do
    resources :places
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :trip
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/firstpage_controller.rb
class FirstpageController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
require 'byebug'
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /places
  # GET /places.json
  def index
    @itinerary = Trip.find(params[:trip_id])
    @places = Place.where(trip_id: params[:trip_id])
    @trip = params[:trip_id]

    @place = Place.new
    @location = params[:location]
    @details = Trip.find(params[:trip_id])

  end

  # GET /places/1
  # GET /places/1.json
  def show
    @trip = Trip.find(params[:trip_id])
    @place = Place.find(params[:id])
  end

  # GET /places/new
  def new
    puts "PARAMS: #{params[:location]}"
    @place = Place.new
    @location = params[:location]
    @trip = params[:trip_id]
    @details = Trip.find(params[:trip_id])

  end

  # GET /places/1/edit
  def edit
    @trip = Trip.find(params[:trip_id])
    @place = Place.find(params[:id])

    @places = Place.where(trip_id: params[:trip_id])
    @others = @places.where.not(id: params[:id])

  end

  # POST /places
  # POST /places.json
  def create
    # params = { place: {location: "foo"} }
    # puts "PARAMS: #{params[:place]}"
    @trip = Trip.find(params[:trip_id])
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to trip_places_path(@trip), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    @trip = Trip.find(params[:trip_id])
    @place = Place.find(params[:id])
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to trip_places_path(@trip), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to trip_places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :content, :date, :location, :trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

 def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new

  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
      else
        format.html { render :new }
      end
    end

  end

   def update

    @trip = Trip.find(params[:id])
    @trip.update(trip_params)

    redirect_to trips_path
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :description, :start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firstpage_helper.rb
module FirstpageHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/firstpage/index.html.erb
<h1>Travela</h1>

<%= javascript_pack_tag 'hello_react' %>
<%= javascript_include_tag 'search' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with scope: :place, url: trip_places_path(@trip), local: true do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, value: @location %>
  </div>

  <div class="field">
    <%= form.label :activity %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.hidden_field :trip_id, value: @trip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Edit Location</h1>
<h1><%= @trip.title %>: Your Itinerary</h1>
<p>Description: <%= @trip.description %></p>
<p>Dates: <%= @trip.start_date %> - <%= @trip.end_date %></p>
<%= link_to 'Add a Location', new_trip_place_path %>

<table>
  <thead>
    <tr>
    	<th class="first">No.</th>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
  	<%= form_with scope: :place, url: trip_place_path, method: 'put', local: true do |form| %>
      <tr>
      	<td><%= @place.id %></td>
        <td><%= form.text_field :title %></td>
        <td><%= form.text_area :content %></td>
        <td><%= form.date_field :date %></td>
        <td><%= form.text_area :location, value: @location %></td>
        <%= form.hidden_field :trip_id %>
      </tr>
      <% @others.each do |other| %>
      <tr>
      	<td><%= other.id %></td>
        <td><%= other.title %></td>
        <td><%= other.content %></td>
        <td><%= other.date %></td>
        <td><%= other.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Maps', trips_path %>
<%= link_to 'Back to Itinerary', trip_places_path(@trip) %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @itinerary.title %>: Your Itinerary</h1>
<p>Description: <%= @itinerary.description %></p>
<p>Dates: <%= @itinerary.start_date %> - <%= @itinerary.end_date %></p>
<button class="add-location" onclick="showDiv()">Add a New Location</button>
<%#= link_to 'Add a Location', new_trip_place_path %>

<div id="new-form"><%= render 'form', place: @place %></div>


<% if (@places.length > 0 ) %>
<table>
  <thead>
    <tr>
    	<th class="first">No.</th>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th>Location</th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
      	<td><%= place.id %></td>
        <td><%= place.title %></td>
        <td><%= place.content %></td>
        <td><%= place.date %></td>
        <td><%= place.location %></td>
        <td class="action"><%= link_to 'Edit', edit_trip_place_path(@itinerary, place) %> <%= link_to 'Delete', trip_place_path(@itinerary, place),
		        method: :delete,
		        data: { confirm: 'Really Meh?' } %><td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
	<p>Click on "Add a Location" to add some places to visit on your trip!</p>
<% end %>
<br>

<%= link_to 'Back to Maps', trips_path %>

app/views/places/new.html.erb
<h1><%= @details.title %>: Add a New Location</h1>
<p>Description: <%= @details.description %></p>
<p>Dates: <%= @details.start_date %> - <%= @details.end_date %></p>

<%= render 'form', place: @place %>

<%= link_to 'Back', trip_places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @place.content %>
</p>

<%= link_to 'Edit', edit_trip_place_path(@trip, @place) %> |
<%= link_to 'Back', trip_places_path %>

app/views/trips/edit.html.erb
<h1>Make changes to your trip</h1>

<%= form_with model: @trip, local: true do |form| %>

	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description %>
	</p>

	<p>
		<%= form.label :start_date %><br>
		<%= form.date_field :start_date %>
	</p>

		<p>
			<%= form.label :end_date %><br>
			<%= form.date_field :end_date %>
		</p>

	<p>
		<%= form.submit "Update" %>
	</p>

<% end %>

<%= link_to 'Back to Maps', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>
<div class="header-pic"><img src="./assets/scenery1.jpg" /><img src="./assets/scenery2.jpg" /><img src="./assets/scenery3.jpg" /><img src="./assets/scenery4.jpg" /></div>
<h1 class="main-header">Travela</h1>
<%= link_to 'Add a New Trip', new_trip_path %>
<table>
	<thead>
		<tr>
			<th>Trip Name</th>
			<th>Description</th>
			<th>Start Date</th>
			<th>End Date</th>
		</tr>
	</thead>

	<tbody>
		<% @trips.each do |trip| %>
			<tr>
				<td><%= trip.title %></td>
				<td><%= trip.description %></td>
				<td><%= trip.start_date %></td>
				<td><%= trip.end_date %></td>
				<td class="action"><%= link_to 'View', trip_places_path(trip) %>
					<%= link_to 'Edit', edit_trip_path(trip) %>
					<%= link_to 'Delete', trip_path(trip),
		        method: :delete,
		        data: { confirm: 'Really Meh?' } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>
<%= javascript_pack_tag 'hello_react' %>
<%= content_tag :div,
  id: "trips_data",
  data: @trips.to_json do %>
<% end %>
<%= javascript_include_tag 'maps' %>

app/views/trips/new.html.erb
<h1>Create a New Trip</h1>

<%= form_with scope: :trip, url: trips_path, local: true do |form| %>

	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description %>
	</p>

	<p>
		<%= form.label :start_date %><br>
		<%= form.date_field :start_date %>
	</p>

		<p>
			<%= form.label :end_date %><br>
			<%= form.date_field :end_date %>
		</p>

	<p>
		<%= form.submit %>
	</p>
<% end %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @trip.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @trip.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @trip.end_date %>
</p>


<%= link_to 'Back', trips_path %>